cmake_minimum_required(VERSION 3.20.0)

list(APPEND BOARD_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
find_package(Zephyr REQUIRED)

project(my_zephyr_app)

# target_sources(app PRIVATE 
#                src/main.cpp
#             #    drivers/our_driver/our_driver.c
#                  drivers/our_driver/our_driver.h
#                )
# target_include_directories(app PRIVATE include)
add_subdirectory(src)
target_include_directories(app PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/drivers/our_driver)
add_subdirectory(drivers/our_driver)